export enum CampaignStatus {
  SCHEDULE_PENDING = 'SCHEDULE_PENDING',
  SCHEDULED = 'SCHEDULED',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  COMPLETED_WITH_FAILURES = 'COMPLETED_WITH_FAILURES',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
}

export enum EmailStatus {
  SCHEDULE_PENDING = 'SCHEDULE_PENDING',
  SCHEDULED = 'SCHEDULED',
  SENDING = 'SENDING',
  SENT = 'SENT',
  FAILED = 'FAILED',
}

export enum AttemptStatus {
  RESERVED = 'RESERVED',
  SENDING = 'SENDING',
  SENT = 'SENT',
  FAILED = 'FAILED',
  UNKNOWN = 'UNKNOWN',
}

export enum OutboxStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  DONE = 'DONE',
  FAILED = 'FAILED',
}

export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  SMTP_TRANSIENT_ERROR = 'SMTP_TRANSIENT_ERROR',
  SMTP_PERMANENT_ERROR = 'SMTP_PERMANENT_ERROR',
  IDEMPOTENCY_MISMATCH = 'IDEMPOTENCY_MISMATCH',
}
